In [1]:
import numpy as np 

In [10]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(list_)

In [11]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
# to print the data types of both the variables

In [12]:
type(list_)

list

In [14]:
type(array_list)

numpy.ndarray

# Q2. Write a code to print the data type of each and every element of both the variables list_ and 
# arra_list.

In [15]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


# Will there be any difference in the data type of the elements present in both the variables, list_ and 
# arra_list? If so then print the data types of each and every element present in both the variables, list_ 
# and arra_list

In [16]:
array_list = np.array(object = list_, dtype = int)

In [18]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [19]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:

# (i)	 shape

# (ii) size

In [20]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
# creation function.

# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
zeros_np = np.zeros((3,3))

In [24]:
zeros_np.shape

(3, 3)

In [25]:
zeros_np.size

9

# Q6. Create an identity matrix of shape (5,5) using numpy functions?

# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [28]:
identity_mat = np.eye(5,5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
